### ISSUE TITLE
Infinite reload on localhost

### ISSUE THREAD

**Issue by mvcodelabs** [wobsoriano/nuxt-clerk-template#1]
Hi, thanks for this playground and the h3-clerk package, i've been looking for something like this for a while.

I'm trying this playground and on localhost it goes on an infinite loop reloading the page. I tried it on a codespace and it worked the first time.

**Comment by wobsoriano** [comment]
I have this issue as well. This seems related https://github.com/clerkinc/javascript/issues/865

**Comment by wobsoriano** [comment]
https://github.com/clerkinc/javascript/issues/1436

**Comment by wobsoriano** [comment]
@fanckush thanks for linking your issue here. It's definitely the reason that's stopping me from publishing a Nuxt module ([h3-clerk](https://github.com/wobsoriano/h3-clerk) and [vue-clerk](https://vue-clerk.vercel.app/) combined).

This is how they handle infinite reloads in Next

https://github.com/clerkinc/javascript/blob/559a0e6e209d8f8662ededdd16421ad38384c3db/packages/nextjs/src/server/authMiddleware.ts#L363
